language: php
php:
  - 5.4
#  - 5.5
#  - 5.6
#  - hhvm
#  - nightly
env:
#  - DB=mysql
#  - DB=sqlite
install:
#  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - composer install
  - pyrus install pear/PHP_CodeSniffer
  - sudo apt-get update
  - sudo apt-get install php5-xsl php5-curl sqlite3 php5-sqlite
  - sudo apt-get install mysql-server php5-mysql
before_script:
#  - sudo service apache2 restart
  - phpenv config-add ./dev-tools/travis-php-env.ini
  - phpenv rehash
# set up the databases
#  - if [[ "$DB" == "sqlite" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
script: make tests
